import React, { useState, useEffect } from 'react';
import { 
  ArrowLeft, 
  ShieldCheck, 
  Lock, 
  Zap, 
  Sparkles, 
  FolderDown, 
  CheckCircle, 
  Tag, 
  Package, 
  Smartphone, 
  CreditCard, 
  Receipt, 
  Check, 
  Clock,
  ExternalLink
} from 'lucide-react';

import { getCoupons } from '../supabase';

export default function CheckoutPage({ 
  product, 
  user, 
  onBack, 
  onPaymentComplete 
}) {
  const [fullName, setFullName] = useState(user?.name || '');
  const [email, setEmail] = useState(user?.email || '');
  const [phone, setPhone] = useState(user?.phone || '');
  const hasBumpOffer = Boolean(
    product.enable_bump_offer === true || 
    (product.enable_bump_offer !== false && product.bump_title && product.id !== 'prod-course-ai')
  );
  const [addUpsell, setAddUpsell] = useState(hasBumpOffer);
  const [couponCode, setCouponCode] = useState('');
  const [discountAmount, setDiscountAmount] = useState(0);
  const [couponApplied, setCouponApplied] = useState(false);
  const [couponError, setCouponError] = useState('');
  const [availableCoupons, setAvailableCoupons] = useState([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStatus, setProcessingStatus] = useState('');

  // Fetch admin coupons
  useEffect(() => {
    (async () => {
      try {
        const coupons = await getCoupons();
        setAvailableCoupons(coupons || []);
      } catch (e) {}
    })();
  }, []);

  // Dynamically load Razorpay SDK
  useEffect(() => {
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.async = true;
    document.body.appendChild(script);
    return () => {
      if (document.body.contains(script)) {
        document.body.removeChild(script);
      }
    };
  }, []);

  const basePrice = product.price;
  const upsellPrice = product.bump_price || 99;
  const upsellTitle = product.bump_title || "500+ CapCut XML Presets & Viral SFX Vault";
  const upsellDesc = product.bump_desc || "Pre-configured cinematic text animations, transitions & 300+ viral sound effects.";
  const subtotal = basePrice + (hasBumpOffer && addUpsell ? upsellPrice : 0);
  const total = Math.max(0, subtotal - discountAmount);


  const handleApplyCoupon = (e) => {
    e.preventDefault();
    setCouponError('');
    const clean = couponCode.trim().toUpperCase();
    if (!clean) {
      setCouponError('Please enter a coupon code.');
      return;
    }

    // Only allow coupons generated by Admin in Supabase
    const matched = availableCoupons.find(
      c => c.code && c.code.trim().toUpperCase() === clean && (c.is_active !== false)
    );

    if (matched) {
      let disc = 0;
      if (matched.discount_type === 'percentage') {
        disc = Math.round((subtotal * (Number(matched.discount_value) || 0)) / 100);
      } else {
        disc = Math.min(subtotal, Number(matched.discount_value) || 0);
      }
      setDiscountAmount(disc);
      setCouponApplied(true);
      setCouponError('');
    } else {
      setCouponApplied(false);
      setDiscountAmount(0);
      setCouponError('Wrong coupon code! This coupon is invalid or expired.');
    }
  };

  const handlePayNow = async (e) => {
    e.preventDefault();
    if (!phone || phone.length < 10) {
      alert('Please enter your 10-digit WhatsApp number to receive your Drive link!');
      return;
    }

    const razorpayKey = import.meta.env.VITE_RAZORPAY_KEY_ID || process.env.REACT_APP_RAZORPAY_KEY_ID;

    // If real Razorpay key is present and SDK loaded, open live Razorpay popup
    if (razorpayKey && window.Razorpay) {
      try {
        setIsProcessing(true);
        setProcessingStatus('Initializing Secure Razorpay Gateway...');

        let serverOrderId = null;

        // Try server-side order creation first for 100% verified transactions
        try {
          const res = await fetch('/api/create-razorpay-order', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              amount: total,
              receipt: `rcpt_${product.id}_${Date.now()}`,
              notes: {
                productId: product.id,
                productTitle: product.title,
                phone: phone,
                email: email
              }
            })
          });
          if (res.ok) {
            const data = await res.json();
            if (data.orderId) {
              serverOrderId = data.orderId;
            }
          }
        } catch (serverOrderErr) {
          console.warn('Server order creation skipped, using direct checkout:', serverOrderErr);
        }

        const options = {
          key: razorpayKey,
          amount: Math.round(total * 100), // in paise
          currency: 'INR',
          name: 'Bazara',
          description: product.title + (hasBumpOffer && addUpsell ? ` + ${upsellTitle}` : ''),
          image: typeof window !== 'undefined' && window.location.origin ? `${window.location.origin}/logo.png` : 'https://bazara.in/logo.png',
          order_id: serverOrderId || undefined,
          prefill: {
            contact: '+91' + phone,
            email: email || `${phone}@bazara.in`,
            name: fullName || user?.name || ''
          },
          theme: {
            color: '#6E66DB'
          },
          modal: {
            ondismiss: function () {
              setIsProcessing(false);
              setProcessingStatus('');
            }
          },
          handler: async function (response) {
            setProcessingStatus('Payment Received! Verifying & Unlocking Access...');

            const proofId = response.razorpay_payment_id || ('pay_' + Math.random().toString(36).substring(2, 10).toUpperCase());

            // If order_id exists, verify signature via backend API
            if (response.razorpay_signature && response.razorpay_order_id) {
              try {
                await fetch('/api/verify-razorpay-payment', {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({
                    razorpay_order_id: response.razorpay_order_id,
                    razorpay_payment_id: response.razorpay_payment_id,
                    razorpay_signature: response.razorpay_signature
                  })
                });
              } catch (verifyErr) {
                console.warn('Signature verification call error (ignoring to avoid blocking user):', verifyErr);
              }
            }

            const orderData = {
              productId: product.id,
              productTitle: product.title,
              amount: total,
              customerName: fullName || user?.name || 'Customer',
              customerPhone: phone,
              customerEmail: email || `user_${phone.slice(-4)}@bazara.in`,
              upsellIncluded: hasBumpOffer && addUpsell,
              upsellTitle: (hasBumpOffer && addUpsell) ? upsellTitle : null,
              upsellDriveUrl: (hasBumpOffer && addUpsell) ? (product.bump_drive_url || null) : null,
              driveUrl: product.drive_download_url,
              paymentId: proofId,
              razorpayPaymentId: proofId,
              razorpayOrderId: response.razorpay_order_id || serverOrderId || null
            };

            setIsProcessing(false);
            setProcessingStatus('');
            onPaymentComplete(orderData);
          }
        };

        const rzp = new window.Razorpay(options);
        rzp.on('payment.failed', function (resp) {
          setIsProcessing(false);
          setProcessingStatus('');
          alert('Payment Failed: ' + (resp.error?.description || 'Please try again.'));
        });
        rzp.open();
        return;
      } catch (err) {
        setIsProcessing(false);
        setProcessingStatus('');
        console.error('Razorpay popup error:', err);
        alert('Could not open Razorpay gateway. Please check your network or try again.');
        return;
      }
    }

    // If key is missing or SDK didn't load
    setIsProcessing(false);
    setProcessingStatus('');
    if (!razorpayKey) {
      alert('Payment Gateway Error: VITE_RAZORPAY_KEY_ID is missing in Vercel Environment Variables. Please set VITE_RAZORPAY_KEY_ID and redeploy.');
    } else {
      alert('Payment Gateway is initializing. Please refresh and try again in 5 seconds.');
    }
  };


  return (
    <div className="min-h-screen pb-20 bg-[#08090E] text-slate-100 selection:bg-emerald-500/30">
      {/* Top Header */}
      <header className="sticky top-0 z-30 px-4 py-3 backdrop-blur-xl bg-[#08090E]/85 border-b border-white/[0.06]">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <button
            onClick={onBack}
            className="p-2 rounded-full glass-panel text-slate-300 hover:text-white border border-white/10 active:scale-95 transition-all cursor-pointer"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-300">
            <Lock className="w-3.5 h-3.5 text-emerald-400" />
            <span>256-Bit Encrypted Checkout</span>
          </div>
          <img src="/logo.png" alt="bazara.in" className="w-7 h-7 rounded-lg object-contain shadow-sm" />
        </div>
      </header>


      <main className="max-w-5xl mx-auto px-4 sm:px-6 pt-4 pb-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          
          {/* Left Column: Order Summary, Upsell Bump & Delivery Details */}
          <div className="lg:col-span-7 space-y-4">
            {/* ================= 1. ORDER SUMMARY ================= */}
            <section className="p-5 rounded-3xl bg-[#131724] border border-white/[0.08] space-y-4 shadow-2xl shadow-black/50 animate-fade-in-up">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
              <Package className="w-4 h-4" />
            </div>
            <h3 className="text-lg font-extrabold text-white tracking-tight">Order Summary</h3>
          </div>

          <div className="border-b border-white/[0.08]" />

          <div className="flex space-x-3.5 items-center">
            <img
              src={product.cover_image}
              alt={product.title}
              className="w-20 aspect-video rounded-xl object-cover border border-white/10 shrink-0 shadow-md transition-transform duration-300 hover:scale-105"
            />
            <div className="space-y-1 flex-1">
              <h4 className="text-xs font-bold text-white line-clamp-2 leading-snug">
                {product.title}
              </h4>
              <div className="flex items-center space-x-2 text-xs">
                <span className="text-base font-extrabold text-emerald-400">₹{product.price}</span>
                {product.original_price && (
                  <span className="text-slate-400 line-through text-xs">₹{product.original_price}</span>
                )}
                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-rose-500/20 text-rose-400 animate-pulse">
                  SAVE {product.discount_percentage || 85}%
                </span>
              </div>
            </div>
          </div>

          {/* Promo Code Input */}
          <form onSubmit={handleApplyCoupon} className="flex items-center space-x-2 pt-1">
            <div className="relative flex-1">
              <Tag className="absolute left-3.5 top-3 w-3.5 h-3.5 text-slate-400" />
              <input
                type="text"
                value={couponCode}
                onChange={(e) => {
                  setCouponCode(e.target.value);
                  if (couponError) setCouponError('');
                }}
                placeholder="Enter coupon code"
                className="w-full pl-9 pr-3 py-2.5 rounded-2xl bg-[#0a0d16] border border-white/10 text-xs text-white uppercase placeholder:normal-case placeholder-slate-500 focus:outline-none focus:border-emerald-400 transition-colors duration-200"
              />
            </div>
            <button
              type="submit"
              className="px-4 py-2.5 rounded-2xl text-xs font-bold bg-white/10 hover:bg-white/20 text-white border border-white/10 active:scale-95 transition-all duration-200 cursor-pointer"
            >
              Apply
            </button>
          </form>
          {couponApplied && (
            <p className="text-[11px] text-emerald-400 font-bold animate-scale-in">
              ✓ Coupon "{couponCode.trim().toUpperCase()}" applied! You saved ₹{discountAmount}
            </p>
          )}
          {couponError && (
            <p className="text-[11px] text-rose-400 font-bold animate-scale-in">
              ✗ {couponError}
            </p>
          )}
        </section>

        {/* ================= 2. ULTRA-PREMIUM ADD-ON BUMP (ONLY IF ENABLED) ================= */}

        {hasBumpOffer && (
          <section 
            onClick={() => setAddUpsell(!addUpsell)}
            className={`relative overflow-hidden p-4 rounded-3xl transition-all duration-300 cursor-pointer shadow-2xl select-none animate-fade-in-up [animation-delay:80ms] ${
              addUpsell 
                ? 'bg-gradient-to-br from-emerald-950/40 via-[#131724] to-[#0d101d] border-2 border-emerald-500 shadow-emerald-500/15 ring-2 ring-emerald-500/20 scale-[1.01]' 
                : 'bg-[#131724]/80 border border-white/10 hover:border-white/20 hover:scale-[1.005]'
            }`}
          >
            {/* Subtle Ambient Radial Glow when selected */}
            {addUpsell && (
              <div className="absolute -top-12 -right-12 w-32 h-32 bg-emerald-500/15 rounded-full blur-2xl pointer-events-none" />
            )}

            <div className="space-y-3 relative z-10">
              {/* Header: Limited Time Offer Badge + Non-breaking Price Tag */}
              <div className="flex items-center justify-between gap-2">
                <span className="px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider bg-rose-500 text-slate-950 flex items-center space-x-1 shrink-0 shadow-sm">
                  <Clock className="w-3 h-3" />
                  <span>SPECIAL ORDER BUMP</span>
                </span>

                {/* Price Tag with NO line break */}
                <div className="flex items-center space-x-1.5 shrink-0 whitespace-nowrap bg-white/[0.04] px-2.5 py-1 rounded-xl border border-white/[0.08]">
                  <span className="text-sm font-black text-emerald-400">+₹{upsellPrice}</span>
                  <span className="text-[9px] font-extrabold px-1.5 py-0.2 rounded bg-emerald-500/20 text-emerald-400">
                    SPECIAL OFFER
                  </span>
                </div>
              </div>

              {/* Product Title & Visual Preview Row */}
              <div className="flex items-start space-x-3">
                <div className={`w-10 h-10 rounded-2xl flex items-center justify-center shrink-0 shadow-lg transition-all ${
                  addUpsell 
                    ? 'bg-gradient-to-tr from-emerald-500 to-teal-400 text-slate-950 shadow-emerald-500/20' 
                    : 'bg-white/10 text-slate-400 border border-white/10'
                }`}>
                  <Sparkles className="w-5 h-5" />
                </div>

                <div className="space-y-1 min-w-0 flex-1">
                  <h4 className="text-xs font-black text-white leading-snug">
                    {upsellTitle}
                  </h4>
                  <p className="text-[11px] text-slate-300 leading-tight">
                    {upsellDesc}
                  </p>
                </div>
              </div>

              {/* Micro Benefits Checklist */}
              <div className="grid grid-cols-1 gap-1.5 py-1 text-[11px] text-slate-300 border-t border-white/[0.06]">
                <div className="flex items-center space-x-2">
                  <div className="w-4 h-4 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0">
                    <Check className="w-2.5 h-2.5 text-emerald-400 stroke-[3]" />
                  </div>
                  <span>1-Click direct Google Drive delivery</span>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-4 h-4 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0">
                    <Check className="w-2.5 h-2.5 text-emerald-400 stroke-[3]" />
                  </div>
                  <span>Instant access along with your main purchase</span>
                </div>
              </div>

              {/* Dynamic Status Toggle Button (No Text Breaking) */}
              <div className={`w-full py-2.5 px-3.5 rounded-2xl font-bold text-xs flex items-center justify-between transition-all select-none ${
                addUpsell 
                  ? 'bg-emerald-500 text-slate-950 shadow-lg shadow-emerald-500/25' 
                  : 'bg-white/5 hover:bg-white/10 text-slate-200 border border-white/10'
              }`}>
                <div className="flex items-center space-x-2 min-w-0">
                  <div className={`w-4 h-4 rounded-full flex items-center justify-center shrink-0 ${
                    addUpsell ? 'bg-slate-950 text-emerald-400' : 'border border-white/40'
                  }`}>
                    {addUpsell && <Check className="w-3 h-3 stroke-[3]" />}
                  </div>
                  <span className="truncate">
                    {addUpsell ? 'Upgrade Added to Order' : 'Tap to Add Upgrade'}
                  </span>
                </div>
                <span className="shrink-0 whitespace-nowrap ml-2 text-[11px] font-black">
                  {addUpsell ? `INCLUDED (+₹${upsellPrice}) ✓` : `+₹${upsellPrice}`}
                </span>
              </div>
            </div>
          </section>
        )}

        {/* ================= 3. DELIVERY DETAILS (NOW THIRD) ================= */}

        <section className="p-5 rounded-3xl bg-[#131724] border border-white/[0.08] space-y-4 shadow-2xl shadow-black/50 animate-fade-in-up [animation-delay:120ms]">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
                <Smartphone className="w-4 h-4" />
              </div>
              <h3 className="text-lg font-extrabold text-white tracking-tight">Delivery Details</h3>
            </div>
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 animate-pulse">
              Instant G-Drive
            </span>
          </div>

          <div className="border-b border-white/[0.08]" />

          <div className="space-y-3">
            <div>
              <label className="text-xs font-bold text-slate-300 block mb-1.5">
                Full Name (Optional)
              </label>
              <input
                type="text"
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                placeholder="Enter your name"
                className="w-full px-4 py-3 rounded-2xl bg-[#0a0d16] border border-white/10 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-400 transition-colors duration-200"
              />
            </div>

            <div>
              <label className="text-xs font-bold text-slate-300 block mb-1.5">
                WhatsApp Mobile Number <span className="text-rose-400">*</span>
              </label>
              <div className="flex items-center space-x-2">
                <span className="px-3.5 py-3 rounded-2xl bg-[#0a0d16] border border-white/10 text-xs font-bold text-slate-300">
                  +91
                </span>
                <input
                  type="tel"
                  maxLength={10}
                  value={phone}
                  onChange={(e) => setPhone(e.target.value.replace(/\D/g, ''))}
                  placeholder="Enter 10-digit number"
                  className="w-full px-4 py-3 rounded-2xl bg-[#0a0d16] border border-white/10 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-400 transition-colors duration-200"
                  required
                />
              </div>
              <p className="text-[11px] text-slate-400 mt-1">Direct Google Drive access link will be sent to this WhatsApp.</p>
            </div>

            <div>
              <label className="text-xs font-bold text-slate-300 block mb-1.5">
                Email Address (Optional)
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="yourname@gmail.com"
                className="w-full px-4 py-3 rounded-2xl bg-[#0a0d16] border border-white/10 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-400 transition-colors duration-200"
              />
            </div>
          </div>
        </section>

          </div>

          {/* Right Column: Sticky Payment Gateway & Order Breakdown on Desktop */}
          <div className="lg:col-span-5 space-y-4 lg:sticky lg:top-20">
            {/* ================= 4. SECURE PAYMENT GATEWAY & BILL ================= */}
            <section className="p-5 rounded-3xl bg-[#131724] border border-white/[0.08] space-y-4 shadow-2xl shadow-black/50 animate-fade-in-up [animation-delay:160ms]">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2.5">
                  <div className="w-8 h-8 rounded-xl bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center text-emerald-400 shadow-md shadow-emerald-500/10">
                    <Lock className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="flex items-center space-x-1.5">
                      <h3 className="text-sm font-extrabold text-white tracking-tight">Payment Gateway</h3>
                      <span className="px-2 py-0.5 rounded-full text-[9px] font-black tracking-wider bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                        100% SECURE CHECKOUT
                      </span>
                    </div>
                    <span className="text-[10px] text-slate-400">100% RBI Authorized & 256-Bit Encrypted</span>
                  </div>
                </div>
              </div>

              {/* Supported Methods Badge Strip */}
              <div className="p-3 rounded-2xl bg-[#0a0d16] border border-white/[0.06] space-y-2">
                <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center justify-between">
                  <span>All Indian Payment Modes Supported:</span>
                  <span className="text-emerald-400">Zero Extra Fee</span>
                </div>
                <div className="flex flex-wrap gap-1.5 text-[10px] font-bold text-slate-300">
                  <span className="px-2 py-1 rounded-lg bg-white/[0.05] border border-white/[0.06] hover:border-emerald-500/30 transition-colors">Google Pay</span>
                  <span className="px-2 py-1 rounded-lg bg-white/[0.05] border border-white/[0.06] hover:border-emerald-500/30 transition-colors">PhonePe</span>
                  <span className="px-2 py-1 rounded-lg bg-white/[0.05] border border-white/[0.06] hover:border-emerald-500/30 transition-colors">Paytm UPI</span>
                  <span className="px-2 py-1 rounded-lg bg-white/[0.05] border border-white/[0.06] hover:border-emerald-500/30 transition-colors">Any UPI ID</span>
                  <span className="px-2 py-1 rounded-lg bg-white/[0.05] border border-white/[0.06] hover:border-emerald-500/30 transition-colors">Debit/Credit Cards</span>
                  <span className="px-2 py-1 rounded-lg bg-white/[0.05] border border-white/[0.06] hover:border-emerald-500/30 transition-colors">NetBanking</span>
                </div>
              </div>

              <div className="border-b border-white/[0.08]" />

              {/* Price Breakdown */}
              <div className="space-y-2 text-xs text-slate-300">
                <div className="flex justify-between text-slate-400">
                  <span>Main Asset</span>
                  <span className="text-white font-semibold">₹{basePrice}</span>
                </div>
                {hasBumpOffer && addUpsell && (
                  <div className="flex justify-between text-emerald-400 animate-scale-in">
                    <span className="truncate max-w-[200px]">{upsellTitle}</span>
                    <span className="font-bold shrink-0">+₹{upsellPrice}</span>
                  </div>
                )}

                {discountAmount > 0 && (
                  <div className="flex justify-between text-rose-400 animate-scale-in">
                    <span>Discount Coupon</span>
                    <span className="font-bold">-₹{discountAmount}</span>
                  </div>
                )}
                <div className="pt-2 border-t border-white/[0.06] flex justify-between items-baseline text-sm font-black text-white">
                  <span>Total Payable:</span>
                  <span className="text-emerald-400 text-2xl font-black">₹{total}</span>
                </div>
              </div>
            </section>

            {/* Big Action Pay Button */}
            <button
              onClick={handlePayNow}
              disabled={isProcessing}
              className="relative w-full overflow-hidden py-4 rounded-full font-black text-sm uppercase tracking-wider text-slate-950 bg-gradient-to-r from-emerald-400 via-emerald-300 to-teal-400 shadow-2xl shadow-emerald-500/40 hover:shadow-emerald-500/60 active:scale-[0.98] transition-all duration-300 flex items-center justify-center space-x-2 disabled:opacity-80 cursor-pointer interactive-tap animate-pulse-glow"
            >
              <span className="absolute inset-0 w-1/2 h-full bg-gradient-to-r from-transparent via-white/80 to-transparent animate-shimmer-sweep pointer-events-none" />
              <span className="relative z-10 flex items-center space-x-2">
                {isProcessing ? (
                  <>
                    <svg className="animate-spin h-4 w-4 text-slate-950" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span className="animate-pulse">{processingStatus || 'Processing Secure Payment...'}</span>
                  </>
                ) : (
                  <>
                    <Lock className="w-4 h-4" />
                    <span>PAY ₹{total} & GET INSTANT ACCESS 🚀</span>
                  </>
                )}
              </span>
            </button>

            <div className="flex items-center justify-center space-x-1.5 text-xs text-slate-400 text-center">
              <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>Instant Download Link & WhatsApp Confirmation Guaranteed</span>
            </div>
          </div>

        </div>
      </main>

    </div>
  );
}
